app:
  security:
    apiKeys: ${API_KEYS}
    throttle:
      limit: ${THROTTLE_LIMIT:200}
      period: ${THROTTLE_PERIOD:3600000}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: ${ENABLE_SWAGGER_UI:false}
     